# 라이브러리 import

In [1]:
!pip install tensorflow

In [2]:
import pandas as pd
import numpy as np
import random
import tensorflow as tf
print(tf.__version__)

2.7.0


# 데이터

In [3]:
import pandas as pd
import numpy as np

x = [-3,  31,  -11,  4,  0,  22, -2, -5, -25, -14]
y = [ -2,   32,   -10,   5,  1,   23,  -1,  -4, -24,  -13]

X_train = np.array(x).reshape(-1, 1) # 1차원으로
y_train = np.array(y)

print(X_train.shape, y_train.shape)

(10, 1) (10,)


In [4]:
X_train

array([[ -3],
       [ 31],
       [-11],
       [  4],
       [  0],
       [ 22],
       [ -2],
       [ -5],
       [-25],
       [-14]])

In [5]:
y_train

array([ -2,  32, -10,   5,   1,  23,  -1,  -4, -24, -13])

# 딥러닝 모델 생성 및 학습

In [6]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

# 일단 모델만 생성
model = Sequential() # 객체 생성
model.add(Dense(units=1, activation='linear', input_dim=1)) # Dense 객체 생성, units: 가중치 개수

In [7]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [8]:
model.compile(optimizer='adam', loss='mse', metrics=['mae']) 

In [17]:
model.fit(X_train, y_train, epochs=3000, verbose=0)

In [19]:
model.weights

[<tf.Variable 'dense/kernel:0' shape=(1, 1) dtype=float32, numpy=array([[1.]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(1,) dtype=float32, numpy=array([0.99999976], dtype=float32)>]

In [20]:
model.predict([[11], [12], [13]])

array([[12.],
       [13.],
       [14.]], dtype=float32)